### ISSUE TITLE
Release anytime soon?

### ISSUE THREAD

**Issue by jason-riddle** [logstash-plugins/logstash-codec-cloudtrail#12]
Now that https://github.com/logstash-plugins/logstash-codec-cloudtrail/pull/11 has been merged is there going to be a release anytime soon?

**Comment by KashifSaadat** [comment]
Looks like this has been released now (v3.0.0): https://github.com/logstash-plugins/logstash-codec-cloudtrail/releases/tag/v3.0.0

**Comment by jason-riddle** [comment]
Yep, I'll go ahead and close this.
