### ISSUE TITLE
Cloudtrail codec error after 3.0.0

### ISSUE THREAD

**Issue by adeliarisk** [logstash-plugins/logstash-codec-cloudtrail#13]
Hi - posted this issue on the discussion boards at Elastic, but never got a response: https://discuss.elastic.co/t/cloudtrail-codec-error-after-new-release/70478

Hi - I just downloaded and installed the newly-released cloudtrail codec. Command to install was:
./bin/logstash-plugin install logstash-codec-cloudtrail

The only change I made in my .conf file was to go from "json" codec to "cloudtrail" codec in input. The pipeline that was working previously but is now broken.

Here are the errors I receive over and over:

20:02:42.044 [[main]<s3] ERROR logstash.pipeline - A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::S3 bucket=>"redacted", access_key_id=>"redacted", secret_access_key=>"redacted", codec=><LogStash::Codecs::CloudTrail id=>"cloudtrail_82d45f40-1490-457e-9407-47d1411e533b", enable_metric=>true, charset=>"UTF-8">, region=>"us-west-2", id=>"redacted", enable_metric=>true, delete=>false, interval=>60, temporary_directory=>"/tmp/logstash">
Operating system: ubuntu 16.04
Elasticsearch version: 5.1.1

Here's my .conf file:

input {
s3 {
bucket => 'redacted'
access_key_id => 'redacted'
secret_access_key => 'redacted'
codec => "cloudtrail"
region => "us-west-2"
}
}

filter {
geoip {
source => "sourceIPAddress"
}
}

output {
elasticsearch {
hosts => "redacted:9243"
user => "redacted"
password => "redacted"
ssl => true
index => "redacted-%{+YYYY.MM.dd}"
document_type => "redacted"
}
}

**Comment by corey-hammerton** [comment]
I get the same thing on Logstash 5.5.2 after running `logstash-plugin install logstash-codec-cloudtrail`

[2017-08-30T16:17:55,145][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::S3 access_key_id=>"redacted", bucket=>"redacted", codec=><LogStash::Codecs::CloudTrail id=>"cloudtrail_7bb5b2d4-18a6-4a47-b564-b6a0a3f57e31", enable_metric=>true, charset=>"UTF-8">, id=>"s3", prefix=>"redacted", region=>"redacted", secret_access_key=>"redacted", temporary_directory=>"/tmp/logstash", add_field=>{"[@metadata][type]"=>"cloudtrail", "[@metadata][pipeline]"=>""}, tags=>["cloud", "s3"], enable_metric=>true, delete=>false, interval=>60>
  Error: undefined method `has_key?' for nil:NilClass

**Comment by hmissi** [comment]
i've got the same error !

**Comment by jsvd** [comment]
https://github.com/logstash-plugins/logstash-codec-cloudtrail/pull/18 has been merged, closing this

**Comment by morganchristiansson** [comment]
Wooo! Can we get a new release on rubygems too? https://rubygems.org/gems/logstash-codec-cloudtrail

**Comment by jsvd** [comment]
published: https://rubygems.org/gems/logstash-codec-cloudtrail/versions/3.0.4
