### ISSUE TITLE
requestParameters nil not handled, undefined method `has_key?' for nil:NilClass

### ISSUE THREAD

**Issue by pdebnath** [logstash-plugins/logstash-codec-cloudtrail#15]
I just used the latest version of this codec 3.0.2 with the latest 5.4.3 ES/Logstash for AWS CloudTrail logs. The codec works for a bit and then errors out. Digging more, I see that requestParameters is assumed to be a Hash in lib/logstash/codecs/cloudtrail.rb. There are CloudTrail logs which have "requestParameters"=>nil in the event, and the codec errors out. There needs to be a check in the code for the class of requestParameter (if event['requestParameters'].class == Hash). Hope this helps others encountering the same issue.

**Comment by zombyte** [comment]
Thanks for the guidance, pdebnath. I'm new to this plugin and Ruby in general. Can anyone provide an in-line code display of the changes that need to be made until an official update is released? Thanks!

**Comment by pdebnath** [comment]
Something along these lines may work, in cloudtrail.rb, though I have not tested all CloudTrail scenario.

  public
  def decode(data)
    decoded = LogStash::Json.load(@converter.convert(data))
    decoded['Records'].each do |event|
      event['@timestamp'] = event.delete('eventTime')

      @logger.debug("Event: #{event}")

      if event.has_key?("requestParameters")
        if event['requestParameters'].class == Hash
          if event['requestParameters'].has_key?("disableApiTermination")
            if event['requestParameters']['disableApiTermination'].class != Hash
              disableApiTermination = event['requestParameters'].delete('disableApiTermination')
              event['requestParameters']['disableApiTermination']= {"value" => disableApiTermination}
            end
          end
        else #"requestParameters"=>nil
          requestParameters = event.delete('requestParameters')
          event['requestParameters']={"value" => requestParameters}
          puts event['requestParameters'].class
        end
      end

      yield LogStash::Event.new(event)
    end
  end # def decode

**Comment by vinogradovs** [comment]
It seems this solution is not full enough, I get another error after applying suggested changes:
Error: undefined method `each' for nil:NilClass

**Comment by philsynek** [comment]
Hi,

unfortunately I am having the same issue. Trying to get Cloudtrail logs into my ELK vagrant box.

root@elk:/var/log/logstash# /usr/share/logstash/bin/logstash-plugin list --verbose
logstash-codec-cloudtrail (3.0.3)

root@elk:/var/log/logstash# /usr/share/logstash/bin/logstash --version
logstash 5.5.1


[2017-08-17T09:28:10,065][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::S3 access_key_id=>"redacted", secret_access_key=>"redacted", bucket=>"redacted", region=>"redacted", delete=>false, interval=>30, type=>"cloudtrail", codec=><LogStash::Codecs::CloudTrail id=>"cloudtrail_df9ccae0-be56-4e8d-b53b-69d2ab1bace4", enable_metric=>true, charset=>"UTF-8">, exclude_pattern=>".\\/CloudTrail-Digest\\/.", id=>"217c63a79e61498ec9ba7f412b72c78d23b6ac8b-3", enable_metric=>true, temporary_directory=>"/tmp/logstash">
  Error: undefined method `has_key?' for nil:NilClass

Kind regards,
Phil

**Comment by corey-hammerton** [comment]
+1

**Comment by TimJDFletcher** [comment]
The plugin works if you downgrade to 3.0.0, you can install this in logstash with: `logstash-plugin install --version 3.0.0 logstash-codec-cloudtrail `

The problematic commit is 9e731fb4eeb8e6cb5495dca137f07ae65157b4b4

**Comment by corey-hammerton** [comment]
Tried testing version 3.0.0 of this codec, still no joy. Got the following error and still had problems parsing the `resources` element into a object data type.

[2017-09-08T09:54:18,018][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::S3 access_key_id=>"redacted", bucket=>"redacted", codec=><LogStash::Codecs::CloudTrail id=>"cloudtrail_4ac47891-d465-4357-9ee2-079c369bd6b6", enable_metric=>true, charset=>"UTF-8">, id=>"s3", prefix=>"redacted", region=>"us-east-1", secret_access_key=>"redacted", temporary_directory=>"/tmp/logstash", add_field=>{"[@metadata][type]"=>"cloudtrail", "[@metadata][pipeline]"=>""}, tags=>["cloud", "s3", "UTC"], enable_metric=>true, delete=>false, interval=>60>
  Error: undefined method `each' for nil:NilClass

**Comment by Menahem1** [comment]
In 3.0.0 it's working thanks @TimJDFletcher

**Comment by outlawza** [comment]
3.0.0 works for me as well. Running Logstash 5.5.1

**Comment by corey-hammerton** [comment]
My bad, 3.0.0 works for me too (on Logstash 5.6.1)

Had 3.0.3 left over from my last run.

**Comment by brewsteropsdev** [comment]
Tried 3.0.0, and still no joy. Any update on this?

**Comment by ggsince88** [comment]
Same issue with v3.0.3 on LS 5.6.5. I removed logstash-codec-cloudtrail v3.0.3 plugin and installed using version 3.0.0 which worked.

**Comment by boodera** [comment]
Worked for me when downgraded cloudtrail plugin, suggested by @TimJDFletcher

**Comment by morganchristiansson** [comment]
I was able to work around this issue by downgrading but then got  ```Error: undefined method `each' for nil:NilClass``` error.

I've created PR https://github.com/logstash-plugins/logstash-codec-cloudtrail/pull/18 to finally fix these errors that have been unfixed for approx 1 year now

**Comment by maiconbaumx** [comment]
Awesome, @morganchristiansson! That worked perfectly to me..

**Comment by jsvd** [comment]
https://github.com/logstash-plugins/logstash-codec-cloudtrail/pull/18 has been merged, closing this

**Comment by cdenneen** [comment]
logstash-codec-cloudtrail (3.0.5) still has same problem.

`responseElements` and `requestParameters` (and their children like `requestParameters.iamInstanceProfile`)
```
[2018-10-23T20:26:49,297][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-cloudtrail-write", :_type=>"_doc", :_routing=>nil}, #<LogStash::Event:0x2b804bc4>], :response=>{"index"=>{"_index"=>"logstash-cloudtrail-000004", "_type"=>"_doc", "_id"=>"H-2bomYBuhFkxAoaxCUs", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"object mapping for [responseElements.role] tried to parse field [role] as object, but found a concrete value"}}}}
[2018-10-23T20:28:28,793][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-cloudtrail-write", :_type=>"_doc", :_routing=>nil}, #<LogStash::Event:0x4cc6643b>], :response=>{"index"=>{"_index"=>"logstash-cloudtrail-000004", "_type"=>"_doc", "_id"=>"gO6domYBuhFkxAoaSECE", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"object mapping for [requestParameters.iamInstanceProfile] tried to parse field [iamInstanceProfile] as object, but found a concrete value"}}}}
```
