### ISSUE TITLE
FR: Cloudtrail default path

### ISSUE THREAD

**Issue by cdenneen** [logstash-plugins/logstash-codec-cloudtrail#2]
Cloudtrail always dumps to /AWSLogs/{accountid}/CloudTrail/{region} so would it be possible to modify so that it only looks in /AWSLogs/*?

**Comment by cdenneen** [comment]
or have s3 support path? (curious if prefix could be set to AWSLogs/*)?

**Comment by tedder** [comment]
there'd need to be a pre-prefix, because cloudtrail can have a prefix. For instance, I dump mine here:

```
bucketname/cloudtrail/AWSLogs/
```

**Comment by cdenneen** [comment]
@tedder good point... under advanced there is a prefix ... so maybe the prefix in s3 would do it?

**Comment by ph** [comment]
@cdenneen The prefix in the s3 input will work for that. 
The codec isn't aware of anything, it just decode the strings.

**Comment by cdenneen** [comment]
@ph great thanks... will give it a shot
