### ISSUE TITLE
s3 input with cloudtrail codec not working with gzipped files

### ISSUE THREAD

**Issue by kevinpauli** [logstash-plugins/logstash-codec-cloudtrail#6]
Not sure if this is a problem with s3 input plugin or the cloudtrail codec...  but I can't seem to get the s3 input with cloudtrail codec working if the file is gzipped (which is the default for cloudtrail). It does work if I download the file, unzip it, and upload it back into a different S3 bucket.

logstash 2.2.2
logstash-input-s3 2.0.4
logstash-codec-cloudtrail 2.0.2

I started out with a normal cloudtrail bucket created by AWS, and a simple config like this:

```
input {   
    s3 {
        bucket => "cloudtrail-logs" 
        codec => cloudtrail {}
    }
}

output {
    stdout { codec => rubydebug }
}
```

When I run logstash with --debug, I see this:

```
S3 input: Adding to objects[] {:key=>"AWSLogs/blahblah/CloudTrail/us-east-1/2016/03/15/blahblah_CloudTrail_us-east-1_20160315T1520Z_qQm4gunsTnNuJosk.json.gz", :level=>:debug, :file=>"logstash/inputs/s3.rb", :line=>"116", :method=>"list_new_files"}
S3 input processing {:bucket=>"cloud-analytics-platform-cloudtrail-logs", :key=>"AWSLogs/blahblah/CloudTrail/us-east-1/2016/03/15/blahblah_CloudTrail_us-east-1_20160315T1520Z_qQm4gunsTnNuJosk.json.gz", :level=>:debug, :file=>"logstash/inputs/s3.rb", :line=>"150", :method=>"process_files"}
S3 input: Download remote file {:remote_key=>"AWSLogs/blahblah/CloudTrail/us-east-1/2016/03/15/blahblah_CloudTrail_us-east-1_20160315T1520Z_qQm4gunsTnNuJosk.json.gz", :local_filename=>"/var/folders/8f/1bjm5vq53c73tjq0yl4560dj1r5f6h/T/logstash/blahblah_CloudTrail_us-east-1_20160315T1520Z_qQm4gunsTnNuJosk.json.gz", :level=>:debug, :file=>"logstash/inputs/s3.rb", :line=>"344", :method=>"download_remote_file"}
Processing file {:filename=>"/var/folders/8f/1bjm5vq53c73tjq0yl4560dj1r5f6h/T/logstash/blahblah_CloudTrail_us-east-1_20160315T1520Z_qQm4gunsTnNuJosk.json.gz", :level=>:debug, :file=>"logstash/inputs/s3.rb", :line=>"182", :method=>"process_local_log"}
Pushing flush onto pipeline {:level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}
Pushing flush onto pipeline {:level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}
Pushing flush onto pipeline {:level=>:debug, :file=>"logstash/pipeline.rb", :line=>"450", :method=>"flush"}
```

And it just keeps printing that last line over and over and never does anything else. If I go look in /var/folders/8f/1bjm5vq53c73tjq0yl4560dj1r5f6h/T/logstash/ I do indeed see a gzipped file, blahblah_CloudTrail_us-east-1_20160315T1520Z_qQm4gunsTnNuJosk.json.gz .

Now, if I unzip this file, and create myself a test bucket, and put the unzipped file into the test bucket, and run logstash pointing at my test bucket, it works fine!

According to the docs at https://www.elastic.co/guide/en/logstash/current/plugins-inputs-s3.html , if the filename ends in .gz then the s3 input should handle it automatically.

**Comment by nukemberg** [comment]
This looks like a bug in the S3 input plugin

**Comment by ghost** [comment]
@kevinpauli I am facing the same issue. Were you able to make this work?

**Comment by kevinpauli** [comment]
No, I eventually gave up on logstash.  I ended up sending logs from CloudTrail to CloudWatch, and then from CloudWatch to ElasticSearch as described here: http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/CWL_ES_Stream.html

**Comment by ghost** [comment]
I just got this working few minutes ago 👍 
Here's my config.. maybe this will help someone.

```
input {                                                               
    s3 {                                                              
      access_key_id => ""                         
      bucket => "bucketname"                                      
      region => "us-east-1"                                           
      secret_access_key => "" 
      prefix => "AWSLogs/AccountID/CloudTrail/us-east-1/"          
      type => "s3"                                                    
      add_field => { source => gzfiles }                              
      codec => cloudtrail {}                                          
    }                                                                 
} 

output {                 
  elasticsearch {        
        host => localhost
        protocol => http 
    }                    
}
```

**Comment by kitforbes** [comment]
Any movement on this issue?

**Comment by nukemberg** [comment]
This is not a bug in the cloudtrail codec. This codec assumes the files where gunzipped the s3 input plugin.
