### ISSUE TITLE
Mapping issues

### ISSUE THREAD

**Issue by catalinvr** [logstash-plugins/logstash-codec-cloudtrail#7]
Hello,

I found the following errors into logstash 

> log: "type"=>"mapper_parsing_exception", "reason"=>"object mapping for [requestParameters.disableApiTermination] tried to parse field [disableApiTermination] as object, but found a concrete value"
> 
> log: "type"=>"mapper_parsing_exception", "reason"=>"object mapping for [requestParameters.filter] tried to parse field [null] as object, but found a concrete value"

That needs to be fixed into the cloudtrail codec.

Thanks

**Comment by nukemberg** [comment]
could you provide more information? what configuration were you using? can you provide sample input?

**Comment by catalinvr** [comment]
I'm using logstash 2.2.1, S3 input and cloudtrail codec. Here is my logstash input config: 

> s3 {
>     bucket => "cloudtrail-012345678912"
>     delete => false
>     interval => 900
>     prefix => "AWSLogs/012345678912/CloudTrail"
>     type => "cloudtrail"
>     codec => "cloudtrail"
>     aws_credentials_file => "/etc/cloudtrail/credentials/012345678912.yml"
>     sincedb_path => "/etc/cloudtrail/tmp/012345678912.sincedb"
>   }

For S3 I set since db path and interval to 900. Everything works ok, but sometimes this error is displayed into logstash log file.

> log: "type"=>"mapper_parsing_exception", "reason"=>"object mapping for [requestParameters.disableApiTermination] tried to parse field [disableApiTermination] as object, but found a concrete value"

cames from "eventSource"=>"ec2.amazonaws.com", "eventName"=>"RunInstances" and here is the cause "disableApiTermination"=>false

> log: "type"=>"mapper_parsing_exception", "reason"=>"object mapping for [requestParameters.filter] tried to parse field [null] as object, but found a concrete value"

cames from "eventSource"=>"iam.amazonaws.com", "eventName"=>"GetAccountAuthorizationDetails", and here is the cause "requestParameters"=>{"filter"=>["User"]}

**Comment by stivi21** [comment]
Hello,
I try patch from [here](https://github.com/logstash-plugins/logstash-codec-cloudtrail/issues/8), but after it i have in logs:

> {:timestamp=>"2016-10-03T11:12:32.628000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::S3 bucket=>\"cloudtrail\", access_key_id=>\"XXX\", secret_access_key=>\"XXX\", prefix=>\"AWSLogs/XXX/CloudTrail/ap-northeast-1/2016/04/20/\", codec=><LogStash::Codecs::CloudTrail spool_size=>50>, region=>\"us-east-1\", use_ssl=>true, delete=>false, interval=>60, temporary_directory=>\"/tmp/logstash\">\n  Error: undefined method `has_key?' for nil:NilClass", :level=>:error}

**Comment by catalinvr** [comment]
@stivi21 try to enable debug mode to logstash and paste the error ( on http://pastebin.com/ and remove sensitive data). I don't know what's the line that causes error.

**Comment by stivi21** [comment]
One line from log is [here](http://pastebin.com/dhUdtygM)

**Comment by catalinvr** [comment]
Can you add the following line 
`@logger.debug("Event: #{event}")`
into the codec on line 14 and kill the logstash service. (You can find it here /opt/logstash/vendor/local_gems/xxxxxxxx/logstash-codec-cloudtrail-2.0.4/lib/logstash/codecs/cloudtrail.rb)
Now you will be able to see the raw message before the error. Can you paste the `event` after you remove sensitive data.

**Comment by stivi21** [comment]
Logs with above line is [here](http://pastebin.com/HxHZDDDd)
